// DO NOT EDIT THIS FILE
// This file was automatically generated from menu_en.txt by ./locale
// Tue Oct 16 15:40:39 2012

#ifndef MENU_L10N_H_
#define MENU_L10N_H_

#ifdef LOCALIZE
#undef LOCALIZE
#endif

#define LOCALIZE(s) s##_en


// ---------------------------------------------------------
// Menu.cc strings

// Splash screen
const static PROGMEM prog_uchar splash1_en[] = "  Sailfish FW   ";
const static PROGMEM prog_uchar splash2_en[] = " -------------- ";
const static PROGMEM prog_uchar splash3_en[] = "Thing 32084 4.5 ";
const static PROGMEM prog_uchar splash4_en[] = " Revision _____ ";

// User view menu
const static PROGMEM prog_uchar uv_msg_en[] = "X/Y Direction";
const static PROGMEM prog_uchar uv_model_en[] = "Model View";
const static PROGMEM prog_uchar uv_user_en[] = "User View";

// JogMode menu
const static PROGMEM prog_uchar j_jog1_en[] = "Jog mode: ";
const static PROGMEM prog_uchar j_jog2_en[] = "   Y+         Z+";
const static PROGMEM prog_uchar j_jog3_en[] = "X- V  X+  (mode)";
const static PROGMEM prog_uchar j_jog4_en[] = "   Y-         Z-";
const static PROGMEM prog_uchar j_jog2_user_en[] = "  Y           Z+";
const static PROGMEM prog_uchar j_jog3_user_en[] = "X V X     (mode)";
const static PROGMEM prog_uchar j_jog4_user_en[] = "  Y           Z-";

const static PROGMEM prog_uchar j_distance0_1mm_en[] = ".1mm";
const static PROGMEM prog_uchar j_distance1mm_en[] = "1mm";
const static PROGMEM prog_uchar j_distanceCont_en[] = "Cont..";

// ExtruderMode menu
const static PROGMEM prog_uchar e_extrude1_en[] = "Extrude: ";
const static PROGMEM prog_uchar e_extrude2_en[] = "(set mm/s)   Fwd";
const static PROGMEM prog_uchar e_extrude3_en[] = " (stop)    (dur)";
const static PROGMEM prog_uchar e_extrude4_en[] = "---/---C     Rev";
const static PROGMEM prog_uchar e_secs_en[] = "SECS";
const static PROGMEM prog_uchar e_blank_en[] = "       ";
const static PROGMEM prog_uchar e_units_en[] = " mm/s ";
const static PROGMEM prog_uchar e_message1_en[] = "Extruder speed:";

// Extruder Too Cold menu
const static PROGMEM prog_uchar etc_warning_en[] = "Tool0 too cold!";
const static PROGMEM prog_uchar etc_cancel_en[] = "Cancel";
const static PROGMEM prog_uchar etc_override_en[] = "Override";

// Mood Light Mode menu
const static PROGMEM prog_uchar ml_mood1_en[] = "Mood: ";
const static PROGMEM prog_uchar ml_mood3_1_en[] = "(set RGB)";
const static PROGMEM prog_uchar ml_msg4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar ml_blank_en[] = "          ";
const static PROGMEM prog_uchar ml_moodNotPresent1_en[] = "Mood Light not";
const static PROGMEM prog_uchar ml_moodNotPresent2_en[] = "present!!";
const static PROGMEM prog_uchar ml_moodNotPresent3_en[] = "See Thingiverse";
const static PROGMEM prog_uchar ml_moodNotPresent4_en[] = "   thing:15347";

// Mood Light Set RGB menu
const static PROGMEM prog_uchar mlsrgb_message1_red_en[] = "Red:";
const static PROGMEM prog_uchar mlsrgb_message1_green_en[] = "Green:";
const static PROGMEM prog_uchar mlsrgb_message1_blue_en[] = "Blue:";
const static PROGMEM prog_uchar mlsrgb_message4_en[] = "Up/Dn/Ent to Set";

// Monitor menu
const static PROGMEM prog_uchar mon_extruder_temp_en[] = "Tool   ---/---\001";
const static PROGMEM prog_uchar mon_platform_temp_en[] = "Bed    ---/---\001";
const static PROGMEM prog_uchar mon_elapsed_time_en[] = "Elapsed:   0h00m";
const static PROGMEM prog_uchar mon_completed_percent_en[] = "Completed:   0% ";
const static PROGMEM prog_uchar mon_time_left_en[] = "TimeLeft:  0h00m";
const static PROGMEM prog_uchar mon_time_left_secs_en[] = "secs";
const static PROGMEM prog_uchar mon_time_left_none_en[] = "   none";
const static PROGMEM prog_uchar mon_zpos_en[] = "ZPos:           ";
const static PROGMEM prog_uchar mon_speed_en[] = "Acc:            ";
const static PROGMEM prog_uchar mon_zpos_mm_en[] = "mm";
const static PROGMEM prog_uchar mon_filament_en[] = "Filament:0.00m  ";
const static PROGMEM prog_uchar mon_copies_en[] = "Copy:           ";
const static PROGMEM prog_uchar mon_of_en[] = " of ";
const static PROGMEM prog_uchar mon_error_en[] = "error!";

// Version menu
const static PROGMEM prog_uchar v_version1_en[] = "Motherboard: _._";
const static PROGMEM prog_uchar v_version2_en[] = "   Extruder: _._";
const static PROGMEM prog_uchar v_version3_en[] = "   Revision:___";
const static PROGMEM prog_uchar v_version4_en[] = "FreeSram: ";

// Cancel Build menu
const static PROGMEM prog_uchar cb_choose_en[] = "Please Choose:";
const static PROGMEM prog_uchar cb_abort_en[] = "Abort Print   ";
const static PROGMEM prog_uchar cb_printAnother_en[] = "Print Another";
const static PROGMEM prog_uchar cb_pauseZ_en[] = "Pause at ZPos ";
const static PROGMEM prog_uchar cb_pause_en[] = "Pause         ";
const static PROGMEM prog_uchar cb_pauseHBPHeat_en[] = "Pause, HBP on ";
const static PROGMEM prog_uchar cb_pauseNoHeat_en[] = "Pause, No Heat";
const static PROGMEM prog_uchar cb_cont_en[] = "Continue Build";
const static PROGMEM prog_uchar cb_back_en[] = "Return to Menu";

// Main menu
const static PROGMEM prog_uchar main_monitor_en[] = "Monitor";
const static PROGMEM prog_uchar main_build_en[] = "Build from SD";
const static PROGMEM prog_uchar main_jog_en[] = "Jog";
const static PROGMEM prog_uchar main_preheat_en[] = "Preheat";
const static PROGMEM prog_uchar main_extruder_en[] = "Extrude";
const static PROGMEM prog_uchar main_homeAxis_en[] = "Home Axis";
const static PROGMEM prog_uchar main_advanceABP_en[] = "Advance ABP";
const static PROGMEM prog_uchar main_steppersS_en[] = "Steppers";
const static PROGMEM prog_uchar main_moodlight_en[] = "Mood Light";
const static PROGMEM prog_uchar main_buzzer_en[] = "Buzzer";
const static PROGMEM prog_uchar main_buildSettings_en[] = "Build Settings";
const static PROGMEM prog_uchar main_profiles_en[] = "Profiles";
const static PROGMEM prog_uchar main_extruderFan_en[] = "Extruder Fan";
const static PROGMEM prog_uchar main_calibrate_en[] = "Calibrate";
const static PROGMEM prog_uchar main_homeOffsets_en[] = "Home Offsets";
const static PROGMEM prog_uchar main_filamentUsed_en[] = "Filament Used";
const static PROGMEM prog_uchar main_currentPosition_en[] = "Position";
const static PROGMEM prog_uchar main_endStops_en[] = "Test End Stops";
const static PROGMEM prog_uchar main_homingRates_en[] = "Homing Rates";
const static PROGMEM prog_uchar main_versions_en[] = "Version";
const static PROGMEM prog_uchar main_eeprom_en[] = "Eeprom";

// Value Set screen
const static PROGMEM prog_uchar vs_message4_en[] = "Up/Dn/Ent to Set";

// Preheat menu
const static PROGMEM prog_uchar ph_heat_en[] = "Heat ";
const static PROGMEM prog_uchar ph_cool_en[] = "Cool ";
const static PROGMEM prog_uchar ph_tool0_en[] = "Tool0";
const static PROGMEM prog_uchar ph_platform_en[] = "Bed";
const static PROGMEM prog_uchar ph_tool0set_en[] = "Set Tool0 Temp";
const static PROGMEM prog_uchar ph_platset_en[] = "Set Bed Temp";
const static PROGMEM prog_uchar ph_message1_en[] = "Tool0 Targ Temp:";
const static PROGMEM prog_uchar ph_message2_en[] = "Bed Target Temp:";

// Home axis menu
const static PROGMEM prog_uchar ha_home1_en[] = "Home Axis: ";
const static PROGMEM prog_uchar ha_home2_en[] = "  Y            Z";
const static PROGMEM prog_uchar ha_home3_en[] = "X   X (endstops)";
const static PROGMEM prog_uchar ha_home4_en[] = "  Y            Z";

// Test End Stops menu
const static PROGMEM prog_uchar tes_test1_en[] = "Test End Stops: ";
const static PROGMEM prog_uchar tes_test2_en[] = "XMin:N    XMax:N";
const static PROGMEM prog_uchar tes_test3_en[] = "YMin:N    YMax:N";
const static PROGMEM prog_uchar tes_test4_en[] = "ZMin:N    ZMax:N";
const static PROGMEM prog_uchar tes_strY_en[] = "Y";
const static PROGMEM prog_uchar tes_strN_en[] = "N";

// Pause menu
const static PROGMEM prog_uchar p_waitForCurrentCommand_en[] = "Entering pause..";
const static PROGMEM prog_uchar p_retractFilament_en[] = "Retract filament";
const static PROGMEM prog_uchar p_clearingBuild_en[] = "Clearing build..";
const static PROGMEM prog_uchar p_heating_en[] = "Heating...      ";
const static PROGMEM prog_uchar p_leavingPaused_en[] = "Leaving pause.. ";
const static PROGMEM prog_uchar p_paused1_en[] = "Paused(";
const static PROGMEM prog_uchar p_paused2_en[] = "   Y+         Z+";
const static PROGMEM prog_uchar p_paused3_en[] = "X- Rev X+  (Fwd)";
const static PROGMEM prog_uchar p_paused4_en[] = "   Y-         Z-";

// Pause @ ZPos menu
const static PROGMEM prog_uchar pz_message1_en[] = "Pause at ZPos:";
const static PROGMEM prog_uchar pz_message4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar pz_mm_en[] = "mm   ";

// Advance ABP menu
const static PROGMEM prog_uchar abp_msg1_en[] = "Advance ABP:";
const static PROGMEM prog_uchar abp_msg2_en[] = "hold key...";
const static PROGMEM prog_uchar abp_msg3_en[] = "           (fwd)";

// Calibrate menu
const static PROGMEM prog_uchar c_calib1_en[] = "Calibrate: Move ";
const static PROGMEM prog_uchar c_calib2_en[] = "build platform";
const static PROGMEM prog_uchar c_calib3_en[] = "until nozzle...";
const static PROGMEM prog_uchar c_calib4_en[] = "          (cont)";
const static PROGMEM prog_uchar c_calib5_en[] = "lies in center,";
const static PROGMEM prog_uchar c_calib6_en[] = "turn threaded";
const static PROGMEM prog_uchar c_calib7_en[] = "rod until...";
const static PROGMEM prog_uchar c_calib8_en[] = "nozzle just";
const static PROGMEM prog_uchar c_calib9_en[] = "touches.";
const static PROGMEM prog_uchar c_homeZ_en[] = "Homing Z...";
const static PROGMEM prog_uchar c_homeY_en[] = "Homing Y...";
const static PROGMEM prog_uchar c_homeX_en[] = "Homing X...";
const static PROGMEM prog_uchar c_done_en[] = "! Calibrated !";
const static PROGMEM prog_uchar c_regen_en[] = "Regenerate gcode";
const static PROGMEM prog_uchar c_reset_en[] = "         (reset)";

// Home Offsets menu
const static PROGMEM prog_uchar ho_message1x_en[] = "X Offset:";
const static PROGMEM prog_uchar ho_message1y_en[] = "Y Offset:";
const static PROGMEM prog_uchar ho_message1z_en[] = "Z Offset:";
const static PROGMEM prog_uchar ho_message4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar ho_mm_en[] = "mm";

// Buzzer Set Repeats menu
const static PROGMEM prog_uchar bsr_message1_en[] = "Repeat Buzzer:";
const static PROGMEM prog_uchar bsr_message2_en[] = "(0=Buzzer Off)";
const static PROGMEM prog_uchar bsr_message4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar bsr_times_en[] = " times ";

// Filament Used Reset menu
const static PROGMEM prog_uchar fur_msg_en[] = "Reset To Zero?";
const static PROGMEM prog_uchar fur_no_en[] = "No";
const static PROGMEM prog_uchar fur_yes_en[] = "Yes";

// Filament Used menu
const static PROGMEM prog_uchar fu_lifetime_en[] = "Lifetime Odo.:";
const static PROGMEM prog_uchar fu_trip_en[] = "Trip Odometer:";
const static PROGMEM prog_uchar fu_but_life_en[] = "(trip)   (reset)";
const static PROGMEM prog_uchar fu_but_trip_en[] = "(life)   (reset)";

// Build Settings menu
const static PROGMEM prog_uchar bs_item1_en[] = "Override Temp";
const static PROGMEM prog_uchar bs_item2_en[] = "ABP Copies (SD)";
const static PROGMEM prog_uchar bs_item3_en[] = "Ditto Print";
const static PROGMEM prog_uchar bs_item4_en[] = "Accel. On/Off";
const static PROGMEM prog_uchar bs_item5_en[] = "Accel. Settings";

// ABP Copies Set menu
const static PROGMEM prog_uchar abp_message1_en[] = "ABP Copies (SD):";
const static PROGMEM prog_uchar abp_message4_en[] = "Up/Dn/Ent to Set";

// Acceleration On Off menu
const static PROGMEM prog_uchar aof_msg1_en[] = "Accelerated";
const static PROGMEM prog_uchar aof_msg2_en[] = "Printing:";
const static PROGMEM prog_uchar aof_off_en[] = "Off";
const static PROGMEM prog_uchar aof_on_en[] = "On";

// Profiles menu
const static PROGMEM prog_uchar pro_defaultProfile_en[] = "Profile?";

// Profile Sub menu
const static PROGMEM prog_uchar ps_msg1_en[] = "Restore";
const static PROGMEM prog_uchar ps_msg2_en[] = "Display Config";
const static PROGMEM prog_uchar ps_msg3_en[] = "Change Name";
const static PROGMEM prog_uchar ps_msg4_en[] = "Save To Profile";

// Profile Change Name menu
const static PROGMEM prog_uchar pcn_message1_en[] = "Profile Name:";
const static PROGMEM prog_uchar pcn_message4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar pcn_blank_en[] = " ";

// Profile Display Settings menu
const static PROGMEM prog_uchar pds_xOffset_en[] = "XOff: ";
const static PROGMEM prog_uchar pds_yOffset_en[] = "YOff: ";
const static PROGMEM prog_uchar pds_zOffset_en[] = "ZOff: ";
const static PROGMEM prog_uchar pds_hbp_en[] = "HBP Temp:   ";
const static PROGMEM prog_uchar pds_tool0_en[] = "Tool0 Temp: ";
const static PROGMEM prog_uchar pds_extruder_en[] = "ExtrdrMM/s: ";

// Current Position menu
const static PROGMEM prog_uchar cp_msg1_en[] = "X:";
const static PROGMEM prog_uchar cp_msg2_en[] = "Y:";
const static PROGMEM prog_uchar cp_msg3_en[] = "Z:";
const static PROGMEM prog_uchar cp_msg4_en[] = "A:";
const static PROGMEM prog_uchar cp_mm_en[] = "mm";

// Unable To Open File menu
const static PROGMEM prog_uchar utof_msg1_en[] = "Failed to open";
const static PROGMEM prog_uchar utof_msg2_en[] = "file.  Name too";
const static PROGMEM prog_uchar utof_msg3_en[] = "long?";
const static PROGMEM prog_uchar utof_cont_en[] = "Continue";

// Accelerated Settings menu
const static PROGMEM prog_uchar as_message1xMaxAccelRate_en[] = "X Max Accel:";
const static PROGMEM prog_uchar as_message1yMaxAccelRate_en[] = "Y Max Accel:";
const static PROGMEM prog_uchar as_message1zMaxAccelRate_en[] = "Z Max Accel:";
const static PROGMEM prog_uchar as_message1aMaxAccelRate_en[] = "Right Max Accel:";
const static PROGMEM prog_uchar as_message1bMaxAccelRate_en[] = "Left Max Accel:";
const static PROGMEM prog_uchar as_message1ExtruderNorm_en[] = "Max Accel:";
const static PROGMEM prog_uchar as_message1ExtruderRetract_en[] = "Max Accel Extdr:";
const static PROGMEM prog_uchar as_message1AdvanceK_en[] = "JKN Advance K:";
const static PROGMEM prog_uchar as_message1AdvanceK2_en[] = "JKN Advance K2:";
const static PROGMEM prog_uchar as_message1ExtruderDeprimeA_en[] = "Extdr.DeprimeR:";
const static PROGMEM prog_uchar as_message1ExtruderDeprimeB_en[] = "Extdr.DeprimeL:";
const static PROGMEM prog_uchar as_message1SlowdownLimit_en[] = "SlowdownEnabled:";
const static PROGMEM prog_uchar as_message1MaxSpeedChangeX_en[] = "MaxSpeedChangeX:";
const static PROGMEM prog_uchar as_message1MaxSpeedChangeY_en[] = "MaxSpeedChangeY:";
const static PROGMEM prog_uchar as_message1MaxSpeedChangeZ_en[] = "MaxSpeedChangeZ:";
const static PROGMEM prog_uchar as_message1MaxSpeedChangeA_en[] = "MaxSpeedChangeR:";
const static PROGMEM prog_uchar as_message1MaxSpeedChangeB_en[] = "MaxSpeedChangeL:";
const static PROGMEM prog_uchar as_message4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar as_blank_en[] = "    ";

// End Stop Config menu
const static PROGMEM prog_uchar esc_message1_en[] = "EndstopsPresent:";
const static PROGMEM prog_uchar esc_message4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar esc_blank_en[] = " ";

// Homing Feed Rates menu
const static PROGMEM prog_uchar hfr_message1x_en[] = "X Home Feedrate:";
const static PROGMEM prog_uchar hfr_message1y_en[] = "Y Home Feedrate:";
const static PROGMEM prog_uchar hfr_message1z_en[] = "Z Home Feedrate:";
const static PROGMEM prog_uchar hfr_message4_en[] = "Up/Dn/Ent to Set";
const static PROGMEM prog_uchar hfr_mm_en[] = "mm/min ";

// Eeprom menu 1
const static PROGMEM prog_uchar e_message_dump_en[] = "EEPROM -> SD";
const static PROGMEM prog_uchar e_message_restore_en[] = "SD -> EEPROM";
const static PROGMEM prog_uchar e_message_erase_en[] = "Erase EEPROM";

// Eeprom menu 2
const static PROGMEM prog_uchar eeprom_message_dump_en[] = "Saving...";
const static PROGMEM prog_uchar eeprom_message_restore_en[] = "Restoring...";
const static PROGMEM prog_uchar eeprom_message_erase_en[] = "Erasing...";
const static PROGMEM prog_uchar eeprom_message_error_en[] = "Error:";

const static PROGMEM prog_uchar eeprom_msg1_en[] = "This menu can";
const static PROGMEM prog_uchar eeprom_msg2_en[] = "make your bot";
const static PROGMEM prog_uchar eeprom_msg3_en[] = "inoperable.";
const static PROGMEM prog_uchar eeprom_msg4_en[] = "Press Y+ to cont";
const static PROGMEM prog_uchar eeprom_msg5_en[] = "Read Failed!";
const static PROGMEM prog_uchar eeprom_msg6_en[] = "EEPROM may be";
const static PROGMEM prog_uchar eeprom_msg7_en[] = "corrupt";
const static PROGMEM prog_uchar eeprom_msg8_en[] = "File not found!";
const static PROGMEM prog_uchar eeprom_msg9_en[] = "* Press ";
const static PROGMEM prog_uchar eeprom_msg10_en[] = "x more!";
const static PROGMEM prog_uchar eeprom_msg11_en[] = "Write Failed!";
const static PROGMEM prog_uchar eeprom_msg12_en[] = "File exists!";
const static PROGMEM prog_uchar eeprom_blank_en[] = "                ";

// Steppers menu
const static PROGMEM prog_uchar step_msg1_en[] = "Stepper Motors:";

// Extruder Fan menu
const static PROGMEM prog_uchar ext_msg1_en[] = "Extruder Fan:";
const static PROGMEM prog_uchar ext_msg2_en[] = "";

// Override GCode Temp menu
const static PROGMEM prog_uchar ogct_msg1_en[] = "Override GCode";
const static PROGMEM prog_uchar ogct_msg2_en[] = "Temperature:";

// Ditto Print menu
const static PROGMEM prog_uchar dp_msg1_en[] = "Ditto Printing:";
const static PROGMEM prog_uchar dp_msg2_en[] = "";


// ---------------------------------------------------------
// MoodLightController.cc strings

const static PROGMEM prog_uchar mood_script0_en[] = "Bot Status";
const static PROGMEM prog_uchar mood_script1_en[] = "Custom RGB";
const static PROGMEM prog_uchar mood_script2_en[] = "Off";
const static PROGMEM prog_uchar mood_script3_en[] = "White";
const static PROGMEM prog_uchar mood_script4_en[] = "Red";
const static PROGMEM prog_uchar mood_script5_en[] = "Green";
const static PROGMEM prog_uchar mood_script6_en[] = "Blue";
const static PROGMEM prog_uchar mood_script7_en[] = "Cyan";
const static PROGMEM prog_uchar mood_script8_en[] = "Magenta";
const static PROGMEM prog_uchar mood_script9_en[] = "Yellow";
const static PROGMEM prog_uchar mood_script10_en[] = "Purple";
const static PROGMEM prog_uchar mood_script11_en[] = "Orange";
const static PROGMEM prog_uchar mood_script12_en[] = "Almond";
const static PROGMEM prog_uchar mood_script13_en[] = "Peach Puff";
const static PROGMEM prog_uchar mood_script14_en[] = "Mint Cream";
const static PROGMEM prog_uchar mood_script15_en[] = "Alice Blue";
const static PROGMEM prog_uchar mood_script16_en[] = "Lavender";
const static PROGMEM prog_uchar mood_script17_en[] = "Misty Rose";
const static PROGMEM prog_uchar mood_script18_en[] = "Slate Gray";
const static PROGMEM prog_uchar mood_script19_en[] = "Gray";
const static PROGMEM prog_uchar mood_script20_en[] = "Light Gray";
const static PROGMEM prog_uchar mood_script21_en[] = "MidnghtBlu";
const static PROGMEM prog_uchar mood_script22_en[] = "DeepSkyBlu";
const static PROGMEM prog_uchar mood_script23_en[] = "OliveGreen";
const static PROGMEM prog_uchar mood_script24_en[] = "ForstGreen";
const static PROGMEM prog_uchar mood_script25_en[] = "Gold";
const static PROGMEM prog_uchar mood_script26_en[] = "Hot Pink";
const static PROGMEM prog_uchar mood_script27_en[] = "Linen";
const static PROGMEM prog_uchar mood_script100_en[] = "WRGB";
const static PROGMEM prog_uchar mood_script101_en[] = "RGB";
const static PROGMEM prog_uchar mood_script102_en[] = "WhiteFlash";
const static PROGMEM prog_uchar mood_script103_en[] = "Red Flash";
const static PROGMEM prog_uchar mood_script104_en[] = "GreenFlash";
const static PROGMEM prog_uchar mood_script105_en[] = "Blue Flash";
const static PROGMEM prog_uchar mood_script106_en[] = "Cyan Flash";
const static PROGMEM prog_uchar mood_script107_en[] = "MgntaFlash";
const static PROGMEM prog_uchar mood_script108_en[] = "Yell Flash";
const static PROGMEM prog_uchar mood_script109_en[] = "Black";
const static PROGMEM prog_uchar mood_script110_en[] = "Hue Cycle";
const static PROGMEM prog_uchar mood_script111_en[] = "Mood Light";
const static PROGMEM prog_uchar mood_script112_en[] = "Candle";
const static PROGMEM prog_uchar mood_script113_en[] = "Water";
const static PROGMEM prog_uchar mood_script114_en[] = "Old Neon";
const static PROGMEM prog_uchar mood_script115_en[] = "Seasons";
const static PROGMEM prog_uchar mood_script116_en[] = "Thundrstrm";
const static PROGMEM prog_uchar mood_script117_en[] = "Stop Light";
const static PROGMEM prog_uchar mood_script118_en[] = "S. O. S.";
const static PROGMEM prog_uchar mood_script_unknown_en[] = "UNKNOWN";

// ---------------------------------------------------------
// LiquidCrystral.cc strings

const static PROGMEM prog_uchar lc_overflow_en[] = "overflow";

#endif // MENU_L10N_H_
